export const departments = [
  { label: 'Admin Block', value: 'ADMIN' },
  { label: 'Aerospace Engineering', value: 'AE' },
  { label: 'Artificial Intelligence and Machine Learning', value: 'AIML' },
  { label: 'Biotechnology', value: 'BT' },
  { label: 'Chemical Engineering', value: 'CH' },
  { label: 'Civil Engineering', value: 'CV' },
  { label: 'Computer Science and Engineering', value: 'CSE' },
  { label: 'Electrical and Electronics Engineering', value: 'EEE' },
  { label: 'Electronics and Communication Engineering', value: 'ECE' },
  { label: 'Electronics and Instrumentation Engineering', value: 'EIE' },
  { label: 'Industrial Engineering and Management', value: 'IEM' },
  { label: 'Information Science and Engineering', value: 'ISE' },
  { label: 'Master of Computer Applications', value: 'MCA' },
  { label: 'Mechanical Engineering', value: 'ME' },
  { label: 'Telecommunication Engineering', value: 'TE' },
];

export const documentTypes = [
  { label: 'National ID', value: 'NID' },
  { label: 'Aadhar Card', value: 'AADHAR' },
  { label: 'Driving License', value: 'DL' },
  { label: 'Company ID', value: 'CID' },
  { label: 'Other', value: 'OTHER' },
];
// Staff organized by department
  export const departmentStaff = {
    AE: [
      { label: 'Dr. Ravindra S Kulkarni - Professor & Head', value: 'AE001' },
      { label: 'Dr. Promio Charles F - Associate Professor', value: 'AE002' },
      { label: 'Dr. R Supreeth - Associate Professor', value: 'AE003' },
      { label: 'Mr. Bhaskar K - Assistant Professor', value: 'AE004' },
      { label: 'Mr. Pranesh Kumar S R - Assistant Professor', value: 'AE005' },
      { label: 'Dr. Benjamin Rohit - Assistant Professor', value: 'AE006' },
      { label: 'Mr. Srinivasan S - Assistant Professor', value: 'AE007' },
      { label: 'Mr. Mukesh M - Assistant Professor', value: 'AE008' },
      { label: 'Group Captain (Retd) Prof.Deepak Bana - Visiting Professor', value: 'AE009' },
      { label: 'Mr. Jitendra Singh - Professor of Practice', value: 'AE010' },
      { label: 'Mr. Srinath Ramakrishnan - Assistant Professor', value: 'AE011' },
    ],
    

    AIML: [
      { label: 'Dr. B. Sathish Babu - Professor and HoD', value: 'AIML001' },
      { label: 'Dr. Vijayalakshmi M.N - Associate Professor', value: 'AIML002' },
      { label: 'Dr. S. Anupama Kumar - Associate Professor', value: 'AIML003' },
      { label: 'Prof. Narasimha Swamy S - Assistant Professor', value: 'AIML004' },
      { label: 'Dr. Somesh Nandi - Assistant Professor', value: 'AIML005' },
      { label: 'Dr. K. Vishwavardhan Reddy - Assistant Professor', value: 'AIML006' },
      { label: 'Prof. Rajesh R M - Assistant Professor', value: 'AIML007' },
      { label: 'Prof. Sonika CT - Assistant Professor', value: 'AIML008' },
      { label: 'Prof. Manasa M - Assistant Professor', value: 'AIML009' },
    ],
    

    BT: [
      { label: 'Dr. Vidya Niranjan - Professor & HoD', value: 'BT001' },
      { label: 'Dr. A H Manjunatha Reddy - Associate Professor', value: 'BT002' },
      { label: 'Dr. Neeta Shiva Kumar - Associate Professor', value: 'BT003' },
      { label: 'Dr. Nagashree N Rao - Associate Professor', value: 'BT004' },
      { label: 'Dr. G Vijaya Kumar - Associate Professor', value: 'BT005' },
      { label: 'Dr. Lingayya Hiremath - Assistant Professor', value: 'BT006' },
      { label: 'Dr. M Rajeswari - Assistant Professor', value: 'BT007' },
      { label: 'Dr. Ajeet Kumar Srivastava - Assistant Professor', value: 'BT008' },
      { label: 'Dr. Shivandappa - Assistant Professor', value: 'BT009' },
      { label: 'Dr. S Narendra Kumar - Assistant Professor', value: 'BT010' },
      { label: 'Dr. Praveen Kumar Gupta - Assistant Professor', value: 'BT011' },
      { label: 'Dr. Trilokchandran B - Assistant Professor', value: 'BT012' },
      { label: 'Dr. H Raju - Assistant Professor', value: 'BT013' },
      { label: 'Dr. Sumathra M - Assistant Professor', value: 'BT014' },
      { label: 'Dr. H G Ashok Kumar - Professor', value: 'BT015' },
      { label: 'Dr. A V Narayan - Associate Professor', value: 'BT016' },
      { label: 'Dr. Ashwani Sharma - Assistant Professor', value: 'BT017' },
    ],
    
    CH: [
      { label: 'Dr. Vinod Kallur - Associate Professor and Head', value: 'CH001' },
      { label: 'Dr. R Suresh - Professor and Associate Dean', value: 'CH002' },
      { label: 'Dr. D Ranganath - Associate Professor and Dean Placement', value: 'CH003' },
      { label: 'Dr. Jagadish H Patil - Associate Professor', value: 'CH004' },
      { label: 'Dr. Basavaraja R J - Associate Professor', value: 'CH005' },
      { label: 'Dr. P L Muralidhara - Assistant Professor', value: 'CH006' },
      { label: 'Dr. Vidya C - Assistant Professor', value: 'CH007' },
      { label: 'Dr. Rajalakshmi Mudbidre - Assistant Professor', value: 'CH008' },
      { label: 'Dr. Manjula Sarode - Assistant Professor', value: 'CH009' },
      { label: 'Dr. Ujwal Shreenag Meda - Assistant Professor', value: 'CH010' },
      { label: 'Anupama V. Joshi - Assistant Professor', value: 'CH011' },
      { label: 'Vinutha Moses - Assistant Professor', value: 'CH012' },
    ],
    

    CV: [
      { label: 'Dr. Radhakrishna - Professor & Head', value: 'CV001' },
      { label: 'Dr. M.V. Renukadevi - Professor', value: 'CV002' },
      { label: 'Dr. V. Anantharama - Associate Professor & Deputy CoE', value: 'CV003' },
      { label: 'Dr. Vinod A R - Associate Professor', value: 'CV004' },
      { label: 'Dr. T. Raghavendra - Associate Professor', value: 'CV005' },
      { label: 'Dr. M. Lokeshwari - Associate Professor', value: 'CV006' },
      { label: 'Dr. S. Nethravathi - Assistant Professor', value: 'CV007' },
      { label: 'Dr. L. Durga Prashanth - Assistant Professor', value: 'CV008' },
      { label: 'Dr. Anand Kumar B.G - Assistant Professor', value: 'CV009' },
      { label: 'Dr. M. Varuna - Assistant Professor', value: 'CV010' },
      { label: 'Dr. Sindhu. D - Assistant Professor', value: 'CV011' },
      { label: 'Dr. Sunil S - Assistant Professor', value: 'CV012' },
      { label: 'Dr. Praveen Kumar K - Assistant Professor', value: 'CV013' },
      { label: 'Dr. K. Gajalakshmi - Assistant Professor', value: 'CV014' },
      { label: 'Dr. Somanath. M. Basutkar - Assistant Professor', value: 'CV015' },
      { label: 'Dr. Venugopal. G - Assistant Professor', value: 'CV016' },
      { label: 'Ram Thilak - Assistant Professor', value: 'CV017' },
      { label: 'Dr. Vikas Mendi - Assistant Professor', value: 'CV018' },
      { label: 'Vageesh H P - Assistant Professor', value: 'CV019' },
      { label: 'Ravikiran S Wali - Assistant Professor', value: 'CV020' },
      { label: 'Shrithi.S.Badami - Assistant Professor', value: 'CV021' },
      { label: 'Shashi Kiran.C.R - Assistant Professor', value: 'CV022' },
      { label: 'Gowtham Prasad M. E. - Assistant Professor', value: 'CV023' },
      { label: 'Ashwin Thammaiah K - Assistant Professor', value: 'CV024' },
    ],

      CSE: [
        { label: 'Dr. Ramakanth Kumar P - Professor & Head', value: 'CSE001' },
        { label: 'Dr. Krishnappa H K - Associate Professor', value: 'CSE002' },
        { label: 'Dr. Deepamala N - Associate Professor', value: 'CSE003' },
        { label: 'Dr. Sowmyarani C N - Associate Professor', value: 'CSE004' },
        { label: 'Dr. Hemavathy R - Associate Professor', value: 'CSE005' },
        { label: 'Dr. K Badari Nath - Associate Professor', value: 'CSE006' },
        { label: 'Dr. Chethana R Murthy - Associate Professor', value: 'CSE007' },
        { label: 'Dr. Pratiba D. - Assistant Professor', value: 'CSE008' },
        { label: 'Dr. Jyoti Shetty - Assistant Professor', value: 'CSE009' },
        { label: 'Dr. Praveena T - Assistant Professor', value: 'CSE010' },
        { label: 'Dr. Vishalakshi Prabhu H - Assistant Professor', value: 'CSE011' },
        { label: 'Prof. Ganashree K C - Assistant Professor', value: 'CSE012' },
        { label: 'Dr. Suma B - Assistant Professor', value: 'CSE013' },
        { label: 'Dr. Pavithra H - Assistant Professor', value: 'CSE014' },
        { label: 'Dr. Prapulla S B - Assistant Professor', value: 'CSE015' },
        { label: 'Dr. Sneha M - Assistant Professor', value: 'CSE016' },
        { label: 'Prof. Manonmani S - Assistant Professor', value: 'CSE017' },
        { label: 'Prof. Deepika Dash - Assistant Professor', value: 'CSE018' },
        { label: 'Dr. Smriti Srivastava - Assistant Professor', value: 'CSE019' },
        { label: 'Dr. Manas M N - Assistant Professor', value: 'CSE020' },
        { label: 'Dr. Veena Gadad - Assistant Professor', value: 'CSE021' },
        { label: 'Prof. Anitha Sandeep - Assistant Professor', value: 'CSE022' },
        { label: 'Prof. Apoorva Udaya Kumar Chate - Assistant Professor', value: 'CSE023' },
        { label: 'Prof. Rajatha - Assistant Professor', value: 'CSE024' },
        { label: 'Prof. Savitri Kulkarni - Assistant Professor', value: 'CSE025' },
      ],
    
      ECE: [
        { label: 'Dr. H. V. Ravish Aradhya - Professor & Associate PG Dean & HOD(I/c)', value: 'ECE001' },
        { label: 'Dr. K.S. Geetha - Professor & Vice-Principal', value: 'ECE002' },
        { label: 'Dr. M. Uttara Kumari - Professor', value: 'ECE003' },
        { label: 'Dr. Usha Rani K. R - Professor', value: 'ECE004' },
        { label: 'Dr. Veena Devi - Associate Professor', value: 'ECE005' },
        { label: 'Dr. Chethana G - Assistant Professor', value: 'ECE006' },
        { label: 'Dr. Sujata D. Badiger - Assistant Professor', value: 'ECE007' },
        { label: 'Dr. Rohini S. Hallikar - Assistant Professor', value: 'ECE008' },
        { label: 'Dr. Sujatha Hiremath - Assistant Professor', value: 'ECE009' },
        { label: 'Dr. Rajani Katiyar - Assistant Professor', value: 'ECE010' },
        { label: 'P. Narashimaraja - Assistant Professor', value: 'ECE011' },
        { label: 'Dr. Govinda Raju M. - Associate Professor', value: 'ECE012' },
        { label: 'Dr. K. A. Nethravathi - Assistant Professor', value: 'ECE013' },
        { label: 'Dr. Shilpa D.R. - Associate Professor', value: 'ECE014' },
        { label: 'Dr. Mahesh A. - Associate Professor', value: 'ECE015' },
        { label: 'Dr. Shushrutha K.S. - Associate Professor', value: 'ECE016' },
        { label: 'Dr. Ramavenkateswaran.N. - Assistant Professor', value: 'ECE017' },
        { label: 'Dr. Roopa J. - Assistant Professor', value: 'ECE018' },
        { label: 'Dr. Abhay A. Deshpande - Associate Professor', value: 'ECE019' },
        { label: 'Dr. Sahana B. - Assistant Professor', value: 'ECE020' },
        { label: 'Ravishankar Holla - Assistant Professor', value: 'ECE021' },
        { label: 'Sowmya Nag K - Assistant Professor', value: 'ECE022' },
        { label: 'Sujata Priyambada Mishra - Assistant Professor', value: 'ECE023' },
        { label: 'Neeta B.Malvi - Assistant Professor', value: 'ECE024' },
        { label: 'Deepika P - Assistant Professor', value: 'ECE025' },
        { label: 'Shwetha Baliga - Assistant Professor', value: 'ECE026' },
        { label: 'Rajithkumar B K - Assistant Professor', value: 'ECE027' },
        { label: 'Anusha L S - Assistant Professor', value: 'ECE028' },
        { label: 'Dr. Saba Farheen. N. S - Assistant Professor', value: 'ECE029' },
        { label: 'S Praveen - Assistant Professor', value: 'ECE030' },
        { label: 'Mrs. Pratibha Kantanavar - Assistant Professor', value: 'ECE031' },
        { label: 'Ms. Sindhu Rajendran - Assistant Professor', value: 'ECE032' },
        { label: 'Mr. Subrahamanya K N - Assistant Professor', value: 'ECE033' },
        { label: 'Dr. Aovuthu Sree Madhuri - Assistant Professor', value: 'ECE034' },
        { label: 'Dr. Avik Banerjee - Assistant Professor', value: 'ECE035' },
        { label: 'Dr. S Ravi Shankar - Visiting Professor', value: 'ECE036' },
        { label: 'Dr. Prakash Biswagar - Professor', value: 'MTech001' },
        { label: 'Dr. Kiran V. - Associate Professor', value: 'MTech002' },
        { label: 'Dr. Jayanthi P.N. - Assistant Professor', value: 'MTech003' },
        { label: 'Dr. Uma B.V. - Professor & Dean(Student Affairs)', value: 'VLSI001' },
        { label: 'Dr. Kariyappa B.S. - Professor', value: 'VLSI002' },
        { label: 'Dr. ShylaShree N - Associate Professor', value: 'VLSI003' },
        { label: 'Dr. Srividya P - Associate Professor', value: 'VLSI004' },
        { label: 'Dr. Sowmya K.B - Assistant Professor', value: 'VLSI005' },
        { label: 'Dr. Eleena Mohapatra - Assistant Professor', value: 'VLSI006' },
      ],
      EIE: [
        { label: 'Dr. CH Renu Madhavi - Associate Professor and HOD', value: 'EIE001' },
        { label: 'Dr. Padmaja K V - Professor', value: 'EIE002' },
        { label: 'Dr. Prasanna Kumar S C - Professor', value: 'EIE003' },
        { label: 'Dr. Shankaraiah - Professor', value: 'EIE004' },
        { label: 'Dr. Thangadurai N - Associate Professor', value: 'EIE005' },
        { label: 'Dr. Sudha K L - Associate Professor', value: 'EIE006' },
      ],
      ISE: [
        { label: 'Dr. B M Sagar - Professor & Head', value: 'ISE001' },
        { label: 'Dr. G T Raju - Professor', value: 'ISE002' },
        { label: 'Dr. Vinay S - Professor', value: 'ISE003' },
        { label: 'Dr. Dilip Kumar S M - Professor', value: 'ISE004' },
        { label: 'Dr. Shobha K R - Professor', value: 'ISE005' },
        { label: 'Dr. Pushpa C N - Associate Professor', value: 'ISE006' },
        { label: 'Dr. Shobha G - Professor', value: 'ISE007' },
        { label: 'Dr. G S Mamatha - Professor & Associate Dean (PG Studies)', value: 'MTech_SE001' },
        { label: 'Dr. Ashwini K.B - Associate Professor', value: 'MTech_SE002' },
        { label: 'Rashmi R. - Assistant Professor', value: 'MTech_SE003' },
        { label: 'Dr. Anala M R - Professor', value: 'MTech_IT001' },
        { label: 'Dr. Padmashree T - Associate Professor', value: 'MTech_IT002' },
        { label: 'Poornima Kulkarni - Assistant Professor', value: 'MTech_IT003' },
        { label: 'Dr. Andhe Dharani - Professor & Director', value: 'MCA001' },
        { label: 'Dr. Usha J - Professor', value: 'MCA002' },
        { label: 'Dr. K S Jasmine - Associate Professor', value: 'MCA003' },
        { label: 'Dr. Sumana M - Associate Professor', value: 'MCA004' },
        { label: 'Dr. Seema S - Associate Professor', value: 'MCA005' },
        { label: 'Dr. Jayalakshmi D S - Associate Professor', value: 'MCA006' },
      ],

    ME: [
      { label: 'Dr. Shanmukha N- Professor and Dean Academics', value: 'ME001' },
      { label: ' Dr. Nanjundaradhya N V - Professor', value: 'ME002' },
      { label: 'Dr. Gopala Krishna H D - Professor and Associate Dean', value: 'ME003' },
      { label: 'Dr. Srihari P V - Associate Professor', value: 'ME004' },
      { label: 'Dr. Suresh B S - Associate Professor', value: 'ME005' },
      { label: 'Dr. Venkatesh P R - Associate Professor', value: 'ME006' },
      { label: 'Dr. Sridhar R - Associate Professor', value: 'ME007' },
      { label: 'Dr. Harisha S K - Associate Professor', value: 'ME008' },
      { label: 'Dr. Mahendra Kumar S - Associate Professor', value: 'ME009' },
      { label: 'Dr. Ratna Pal - Associate Professor', value: 'ME010' },
      { label: 'Dr. Nagesh S - Associate Professor', value: 'ME011' },
      { label: 'Dr. Ramakrishna Hegde - Associate Professor', value: 'ME012' },
      { label: 'Dr. Chandrakumar R - Associate Professor', value: 'ME013' },
      { label: 'Dr. Sourabha Srinivasa Havaldar - Associate Professor', value: 'ME014' },
      { label: 'Keshavamurthy Y C - Associate Professor', value: 'ME015' },
      { label: 'Dr. Mamtha V - Assistant Professor', value: 'ME016' },
      { label: 'Dr. Keshav M - Assistant Professor', value: 'ME017' },
      { label: 'Dr. Girish Kumar R - Assistant Professor', value: 'ME018' },
      { label: 'Dr. Girish V A - Assistant Professor', value: 'ME019' },
      { label: 'Dr. Gangadhar Angadi - Assistant Professor', value: 'ME020' },
      { label: 'Dr. Anjaneya G - Assistant Professor', value: 'ME021' },
      { label: 'Sujan Chakraborty- Assistant Professor', value: 'ME022' },
      { label: ' Jinka Ranganayakalu - Assistant Professor', value: 'ME023' },
      { label: ' Rakesh Kumar- Assistant Professor', value: 'ME024' },
      { label: 'Gajanan - Assistant Professor', value: 'ME025' },
      { label: 'Abhiram E R - Assistant Professor', value: 'ME026' },
      { label: 'Dr. Prapul Chandra A C - Assistant Professor', value: 'ME027' },
      { label: 'Dr. Mahantash M Math - Assistant Professor', value: 'ME028' },
      { label: 'Dr. Krishna M - Professor and Head', value: 'ME029' },
      { label: 'Dr. H N Narasimha Murthy - Professor and   Dean (R&D)', value: 'ME030' },
      { label: 'Dr. Nataraj J R - Assistant Professor', value: 'ME031' },
      { label: ' Dr. Rajkumar G R - Assistant Professor', value: 'ME032' },
      { label: ' Dr. Bharatish A - Assistant Professor', value: 'ME033' },
      { label: 'Dr. Roopa. T.S. - Assistant Professor', value: 'ME034' },
      { label: ' Dr. Ramesh S Sharma - Professor', value: 'ME035' },
      { label: ' Dr. Kirthan L J- Assistant Professor', value: 'ME036' },
      { label: ' Dr. Jagannatha Guptha V L - Assistant Professor', value: 'ME037' },

    ],
    TE: [
      { label: 'Dr. K Sreelakshmi - Professor & Head', value: 'TE001' },
      { label: 'Dr. H V Kumaraswamy - Professor', value: 'TE002' },
      { label: 'Dr. P Nagaraju - Associate Professor', value: 'TE003' },
      { label: 'Dr. Bhagya R - Associate Professor', value: 'TE004' },
      { label: 'Dr. B. Roja Reddy - Associate Professor', value: 'TE005' },
      { label: 'Dr. Premananda B S - Associate Professor', value: 'TE006' },
      { label: 'Dr. Shanthi P. - Associate Professor', value: 'TE007' },
      { label: 'Dr. Usha Padma - Associate Professor', value: 'TE008' },
      { label: 'Prof. T. P. Mithun - Associate Professor', value: 'TE009' },
      { label: 'Dr. Shambulinga M. - Associate Professor', value: 'TE010' },
      { label: 'Prof. Nagendra N N - Associate Professor', value: 'TE011' },
      { label: 'Prof. Mahalakshmi. M. N   - Associate Professor', value: 'TE012' },
      { label: 'Prof. Sandya H B   - Associate Professor', value: 'TE013' },
      { label: 'Prof. Rakesh K R - Associate Professor', value: 'TE014' },
      { label: 'Dr. Nagamani K - Professor', value: 'TE015' },
      { label: 'Dr. K. Saraswathi - Associate Professor', value: 'TE016' },
      { label: 'Dr. Ranjani G - Associate Professor', value: 'TE017' },
    ],
    ADMIN: [
      { label: 'Dr. K N Subramanya - Principal', value: 'ADMIN001' },
      { label: 'Dr. B S Satyanarayana - Director', value: 'ADMIN002' },
      { label: 'Dr. N S Narahari - Dean Academics', value: 'ADMIN003' },
      { label: 'Administrative Office', value: 'ADMIN004' },
      { label: 'Accounts Section', value: 'ADMIN005' },
      { label: 'Examination Section', value: 'ADMIN006' },
    ],
   
    
  };

// Export a helper function to get staff by department
export function getStaffByDepartment(departmentValue: string) {
  console.log('Getting staff for department:', departmentValue);
  const staff = departmentStaff[departmentValue as keyof typeof departmentStaff] || [];
  console.log('Found staff:', staff.length);
  return staff;
} 
